<?xml version="1.0"?> 
<robot name="ackermann_1" xmlns:xacro="http://www.ros.org/wiki/xacro"> 
    
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- MACROS FOR COLORS -->
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    <!-- PROPERTIES FOR SIZES -->
    <xacro:property name="chasis_x" value="0.98"/>
    <xacro:property name="chasis_y" value="0.27"/>
    <xacro:property name="chasis_z" value="0.27"/>
    <xacro:property name="chasis_mass" value="70"/>

    <xacro:property name="wheel_radius" value="0.155"/>
    <xacro:property name="wheel_thickness" value="0.14"/>
    <xacro:property name="wheel_sep" value="0.605"/>
    <xacro:property name="front_rear_sep" value="0.646"/>
    <xacro:property name="wheel_mass" value="0.25"/>
    <xacro:property name="max_steer" value="1.6"/>
    <xacro:property name="mu1" value="2"/>
    <xacro:property name="mu2" value="2"/>
	<!-- Base link -->  

    <link name="base_footprint">
    </link> 

	<!-- Chasis-->  
	<joint name="base_link_joint" type="fixed">
        <parent link="base_footprint"/> 
        <child link="base_link"/> 
        <origin xyz="0 0 0.105" rpy="0 0 0"/> 

    </joint> 

    <link name="base_link"> 

        <visual> 
            <!-- <origin xyz="0 0 ${chasis_z/2}" rpy="0 0 0"/>  -->
            <!-- <geometry> 
            <box size="${chasis_x} ${chasis_y} ${chasis_z}"/> 
            </geometry>  -->
            <!-- <material name="white"/>  -->
        </visual> 

        <collision> 
        <!-- <origin xyz="0 0 ${chasis_z/2}" rpy="0 0 0"/>  -->
        <!-- <geometry> 
                <box size="${chasis_x} ${chasis_y} ${chasis_z}"/> 
        </geometry>  -->
        </collision> 
    </link>    

  
	</robot>



  
  
