controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    ack_cont:
      type: ackermann_steering_controller/AckermannSteeringController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ack_cont:
  ros__parameters:

    publish_rate: 50.0
    base_frame_id: base_link
    front_steering: true
    # open_loop: false
    velocity_rolling_window_size: 4
    position_feedback: true
    use_stamped_vel: false
    rear_wheels_names: [back_right_wheel_joint, back_left_wheel_joint]
    front_wheels_names: [front_right_wheel_rotate_joint,front_left_wheel_rotate_joint]
    wheelbase: 0.5 #distance front to back wheels
    front_wheel_track: 0.36 #distance between front wheels
    rear_wheel_track: 0.36 #distance between back wheels
    # radius of both wheels back/front
    front_wheels_radius: 0.05 
    rear_wheels_radius: 0.05