<?xml version="1.0"?> 
<robot name="ackermann_1" xmlns:xacro="http://www.ros.org/wiki/xacro"> 
    
    <xacro:include filename="inertial_macros.xacro"/>

    <!-- MACROS FOR COLORS -->
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    <!-- PROPERTIES FOR SIZES -->
    <xacro:property name="chasis_x" value="0.94"/>
    <xacro:property name="chasis_y" value="0.39"/>
    <xacro:property name="chasis_z" value="0.28"/>
    <xacro:property name="chasis_mass" value="0.5"/>

    <xacro:property name="wheel_radius" value="0.155"/>
    <xacro:property name="wheel_thickness" value="0.14"/>
    <xacro:property name="wheel_sep" value="0.6"/>
    <xacro:property name="front_rear_sep" value="0.65"/>
    <xacro:property name="wheel_mass" value="1"/>
    <xacro:property name="max_steer" value="0.6458"/>
    <xacro:property name="mu1" value="2"/>
    <xacro:property name="mu2" value="2"/>
	<!-- Base link -->  

    <link name="base_link">
    </link> 

	<!-- Chasis-->  
	<joint name="chasis_joint" type="fixed">
        <parent link="base_link"/> 
        <child link="chasis"/> 
    </joint> 

    <link name="chasis"> 

        <visual> 
            <origin xyz="${chasis_x/2} 0 ${chasis_z/2}" rpy="0 0 0"/> 
            <geometry> 
            <box size="${chasis_x} ${chasis_y} ${chasis_z}"/> 
            </geometry> 
            <material name="white"/> 
        </visual> 

        <collision> 
        <origin xyz="${chasis_x/2} 0 ${chasis_z/2}" rpy="0 0 0"/> 
        <geometry> 
                <box size="${chasis_x} ${chasis_y} ${chasis_z}"/> 
        </geometry> 
        </collision> 
        
        <inertial>
            <mass value="21.02945169536679" />
            <inertia
              ixx="0.0332370959804736"
              ixy="-1.013150489971E-06"
              ixz="-0.00188859201421112"
              iyy="0.111072002332437"
              iyz="-5.13308150598312E-07"
              izz="0.12660862809283" />
          </inertial>
    </link>    

    <gazebo reference="chasis"> 
        <kp>1000000.0</kp>  
        <kd>0.1</kd> 
        <dampingFactor>0</dampingFactor> 
        <material>Gazebo/White</material> 
        <selfCollide>true</selfCollide> 
        <turnGravityOff>false</turnGravityOff> 
        <mu1 value="${mu1}"/> 
        <mu2 value="${mu2}"/> 
        <fdir1 value="0 1 0"/> 
    </gazebo>

    <!--FRONT RIGHT WHEEL ROTATE--> 

    <joint name="front_right_wheel_rotate_joint" type="revolute"> 
        <parent link="chasis"/> 
        <child link="front_right_wheel_rotate"/> 
        <origin xyz="${front_rear_sep + (chasis_x - front_rear_sep)/2} -${wheel_sep/2 + wheel_thickness} 0" rpy="0 0 0" />  

        <axis xyz="0 0 1"/> 
        <limit
      lower="-0.69"
      upper="0.69"
      effort="0"
      velocity="0" />
    </joint> 

    <link name="front_right_wheel_rotate">
        <visual> 
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry> 
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> 
            </geometry> 
            <material name="blue"/> 
        </visual> 

		<collision> 
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
		    <geometry> 
                <sphere  radius="${wheel_radius}"/> 
            </geometry> 
		</collision> 

		<inertial>
            <mass
              value="7.696" />
            <inertia
              ixx="0.063704"
              ixy="0"
              ixz="0"
              iyy="0.063704"
              iyz="0"
              izz="0.11068" />
          </inertial>

	</link>  
    
    <gazebo reference="front_right_wheel_rotate"> 
        <mu1 value="${mu1}"/> 
        <mu2 value="${mu2}"/> 
        <kp  value="10000000.0" /> 
        <kd  value="1.0" /> 
        <fdir1 value="0 1 0"/> 
        <material>Gazebo/Blue</material> 
      </gazebo>

    <!--FRONT RIGHT WHEEL MOVE--> 

    <joint name="front_right_wheel_move_joint" type="continuous"> 
        <parent link="front_right_wheel_rotate"/> 
        <child link="front_right_wheel_move"/> 

        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />  
        <axis xyz="0 0 -1" rpy="0 0 0" /> 
        <dynamics damping="0.0" friction="15"/>
    </joint>

	<link name="front_right_wheel_move"> 

        <visual> 
            <geometry> 
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> 
            </geometry> 
            <material name="blue"/> 
        </visual> 
		
		<collision> 
		    <geometry> 
                <sphere radius="${wheel_radius}"/> 
		    </geometry> 
		</collision>  

        <inertial>
            <mass
              value="7.5613" />
            <inertia
              ixx="0.063626"
              ixy="0"
              ixz="0"
              iyy="0.063626"
              iyz="0"
              izz="0.11054" />
          </inertial>

	</link> 


    <gazebo reference="front_right_wheel_move"> 
        <mu1 value="${mu1}"/> 
        <mu2 value="${mu2}"/> 
        <kp  value="10000000.0" /> 
        <kd  value="1.0" /> 
        <fdir1 value="0 1 0"/> 
        <material>Gazebo/Blue</material> 
    </gazebo>

    <!--FRONT LEFT WHEEL ROTATE--> 
    <joint name="front_left_wheel_rotate_joint" type="revolute"> 
        <parent link="chasis"/> 
        <child link="front_left_wheel_rotate"/> 
        <origin xyz="${front_rear_sep + (chasis_x - front_rear_sep)/2} ${wheel_sep/2 + wheel_thickness} 0" rpy="0 0 0" />  

        <axis xyz="0 0 1"/> 
        <limit
        lower="-0.69"
        upper="0.69"
        effort="0"
        velocity="0" />
    </joint> 

    <link name="front_left_wheel_rotate">
        <visual> 
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
            <geometry> 
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> 
            </geometry> 
            <material name="blue"/> 
        </visual> 

		<collision> 
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
		    <geometry> 
                <sphere radius="${wheel_radius}"/> 
            </geometry> 
		</collision> 

		<inertial>
            <mass value="7.8526" />
            <inertia
              ixx="0.063827"
              ixy="0"
              ixz="0"
              iyy="0.063827"
              iyz="0"
              izz="0.11091" />
          </inertial>

	</link>  
    
    <gazebo reference="front_left_wheel_rotate"> 
        <mu1 value="${mu1}"/> 
        <mu2 value="${mu2}"/>  
        <kp  value="10000000.0" /> 
        <kd  value="1.0" /> 
        <fdir1 value="0 1 0"/> 
        <material>Gazebo/Blue</material> 
      </gazebo>

    <!--LEFT RIGHT WHEEL MOVE--> 

    <joint name="front_left_wheel_move_joint" type="continuous"> 
        <parent link="front_left_wheel_rotate"/> 
        <child link="front_left_wheel_move"/> 

        <origin xyz="0 0 0" rpy="-${pi/2} 0 0" />  
        <axis xyz="0 0 1" rpy="0 0 0" /> 
        <dynamics damping="0.0" friction="15"/>
    </joint>

	<link name="front_left_wheel_move"> 

        <visual> 
            <geometry> 
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> 
            </geometry> 
            <material name="blue"/> 
        </visual> 
		
		<collision> 
		    <geometry> 
                <sphere radius="${wheel_radius}"/> 
		    </geometry> 
		</collision>  

        <inertial>
            <mass
              value="7.7007" />
            <inertia
              ixx="0.063724"
              ixy="0"
              ixz="0"
              iyy="0.063724"
              iyz="0"
              izz="0.11072" />
          </inertial>

	</link> 

    <gazebo reference="front_left_wheel_move"> 
        <mu1 value="${mu1}"/> 
        <mu2 value="${mu2}"/>  
        <kp  value="10000000.0" /> 
        <kd  value="1.0" /> 
        <fdir1 value="0 1 0"/> 
        <material>Gazebo/White</material> 
      </gazebo>

    <!--BACK RIGHT WHEEL--> 

    <joint name="back_right_wheel_joint" type="continuous"> 
        <parent link="chasis"/> 
        <child link="back_right_wheel"/> 
        <origin xyz="${(chasis_x - front_rear_sep)/2} -${wheel_sep/2 + wheel_thickness} 0" rpy="${pi/2} 0 0" />  
        <dynamics damping="0.0" friction="15"/>
        <axis xyz="0 0 -1"/> 
    </joint> 

    <link name="back_right_wheel">
        <visual> 
            <geometry> 
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> 
            </geometry> 
            <material name="blue"/> 
        </visual> 

		<collision> 
		    <geometry> 
                <sphere radius="${wheel_radius}"/> 
            </geometry> 
		</collision> 

		<inertial>
            <mass
              value="7.7133" />
            <inertia
              ixx="0.06373"
              ixy="0"
              ixz="0"
              iyy="0.06373"
              iyz="0"
              izz="0.11073" />
          </inertial>

	</link>  
    
    <gazebo reference="back_right_wheel"> 
        <mu1 value="${mu1}"/> 
        <mu2 value="${mu2}"/> 
        <kp  value="10000000.0" /> 
        <kd  value="1.0" /> 
        <fdir1 value="0 1 0"/> 
        <material>Gazebo/Blue</material> 
      </gazebo>

    <!--BACK LEFT WHEEL--> 
    <joint name="back_left_wheel_joint" type="continuous"> 
        <parent link="chasis"/> 
        <child link="back_left_wheel"/> 
        <origin xyz="${(chasis_x - front_rear_sep)/2} ${wheel_sep/2 + wheel_thickness} 0" rpy="-${pi/2} 0 0" />  
        <dynamics damping="0.0" friction="15"/>
        <axis xyz="0 0 1"/> 
    </joint> 

    <link name="back_left_wheel">
        <visual> 
            <geometry> 
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/> 
            </geometry> 
            <material name="blue"/> 
        </visual> 

		<collision> 
		    <geometry> 
                <sphere radius="${wheel_radius}"/> 
            </geometry> 
		</collision> 

		<inertial>
            <mass
              value="7.6692" />
            <inertia
              ixx="0.063699"
              ixy="0"
              ixz="0"
              iyy="0.063699"
              iyz="0"
              izz="0.11067" />
          </inertial>

	</link>  
    
    <gazebo reference="back_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    <gazebo reference="left_wheel_rear"> 
        <mu1 value="${mu1}"/> 
        <mu2 value="${mu2}"/>  
        <kp  value="10000000.0" /> 
        <kd  value="1.0" /> 
        <fdir1 value="0 1 0"/> 
        <material>Gazebo/Blue</material> 
    </gazebo>
	</robot>



  
  
